version: '3.8'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pasSworD
    ports:
      - 5432:5432

  adminer:
    image: adminer:latest
    restart: always
    depends_on:
      - db
    ports:
      - 4200:8080
