version: '3.8'

services:

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pasSworD
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  adminer:
    image: adminer:latest
    restart: always
    depends_on:
      - db
    ports:
      - 4200:8080
